### PR TITLE
Nes 2096 tenant filter by uuid

### PR DESCRIPTION
**Pull request by pc-m**
Depends-On: https://github.com/wazo-platform/xivo-lib-python/pull/135

### CODE REVIEW

**Comment by pc-m** [comment]
> Build failed. https://zuul.wazo.community/zuul/t/local/buildset/119fc9fcdfcc4bf389418438c04fea3b
> 
> ✔️ [tox-linters ](https://zuul.wazo.community/zuul/t/local/build/5c594588263b4facacdd9ef25846d7a6) SUCCESS in 5m 43s ✔️ [wazo-tox-py39 ](https://zuul.wazo.community/zuul/t/local/build/9e1004e6b64c423e8390eab6c537832e) SUCCESS in 6m 00s ✔️ [debian-packaging-bullseye ](https://zuul.wazo.community/zuul/t/local/build/5589048a6065414a88300576bbfdb941) SUCCESS in 3m 15s ❌ [auth-tox-integration ](https://zuul.wazo.community/zuul/t/local/build/706a206193f140319205485cfe186736) **FAILURE** in 9m 40s

Zuul fails to load lib-python in the container. I changed the path in the docker-compose which fixed the tests on my laptop but it does not seem to work on Zuul

**Comment by pc-m** [comment]
recheck

**Comment by pc-m** [comment]
> Build failed. https://zuul.wazo.community/zuul/t/local/buildset/6ec09df3016b447a89dd857986650743
> 
> ✔️ [tox-linters ](https://zuul.wazo.community/zuul/t/local/build/969ae14def9c4c46bfd1041b497476c8) SUCCESS in 5m 42s ✔️ [wazo-tox-py39 ](https://zuul.wazo.community/zuul/t/local/build/bc6684d1593f4d2485e55c8fb2e0127b) SUCCESS in 6m 12s ✔️ [debian-packaging-bullseye ](https://zuul.wazo.community/zuul/t/local/build/5453cc11d5fb4dbd9764a1c68906de48) SUCCESS in 3m 13s ❌ [auth-tox-integration ](https://zuul.wazo.community/zuul/t/local/build/926fde79b4d94936972f84c7f7111012) **FAILURE** in 9m 27s

Zuul refuses to use the mounted code from xivo-lib-python

**Comment by sduthil** [comment]
recheck

**Review by ja0x — APPROVED** [review]

**Pull request merged**
