### PR TITLE
Pull request for NES-1892-fix-slow-tenants

### PR DESCRIPTION
**Pull request by fblackburn1**
A best fix would be to only use ORM or only NOT use ORM. Mixing plain sql and ORM is not really friendly...

### CODE REVIEW

**Review by pc-m — APPROVED** [review]

**Comment by fblackburn1** [comment]
recheck

**Comment by fblackburn1** [comment]
recheck

**Comment by fblackburn1** [comment]
recheck

**Comment by sduthil** [comment]
recheck

**Comment by sduthil** [comment]
recheck

**Comment by fblackburn1** [comment]
regate

**Pull request merged**
