### PR TITLE
WAZO-1638 reduce iteration number of pbkdf2_hmac

### PR DESCRIPTION
**Pull request by safchain**
100 hash generation

Without this PR:
real	0m18.878s
user	0m18.805s
sys	0m0.023s

With it:
real	0m7.876s
user	0m7.816s
sys	0m0.022s

### CODE REVIEW

**Comment by sboily** [comment]
Nice thank you!

**Comment by sboily** [comment]
Don't work for me. I don't know why but I have 401 with this patch.

**Comment by pc-m** [comment]
There is some more work involved to change the hashing algorithm. I think the following solution would be simple to implement.

1. Add a column `password_hash_algorighm_version` with a default value `0` on the user table
2. Change the default value to `1`
3. Create 2 have 2 functions, one to check passwords against the algorithm version 0 and one for version 1
4. When someone authenticate using its password and it's in version 0 if the login is successful
4.1 Compute the new hash using version 1
4.2 Store the new hash and the hash version

When a new password is created always use the most recent version.

**Comment by safchain** [comment]
@pc-m thanks for the suggestions. Before going further with this I wanted to be sure that we wanted to go that way, meaning changing the authentication algorithm ? I personally would say yes, at least having a upgrade path would worth it.

**Comment by pc-m** [comment]
> @pc-m thanks for the suggestions. Before going further with this I wanted to be sure that we wanted to go that way, meaning changing the authentication algorithm ? I personally would say yes, at least having a upgrade path would worth it.

I think that would certainly help with connections spikes when a service is restarted and tens or hundreds of clients can try to get a new token at the same time.

The 25000 iteration value that we chose was fast enough not to feel too long for the user without taking the responsiveness of wazo-auth itself into account. With the numbers you got I think 10000 is a great compromise.

**Comment by fblackburn1** [comment]
I close this PR, because we don't intend to merge it.
Jira related issue https://wazo-dev.atlassian.net/browse/WAZO-1638

**Pull request closed without merging**
