### PR TITLE
Pull request for WAZO-2572-manage-default-policies

### PR DESCRIPTION
**Pull request by fblackburn1**
Depends-on: https://github.com/wazo-platform/wazo-auth-client/pull/25

Dear reviewer,

Here's my apologies
The implemented feature is really cool and quite useful, but it's probably the
only good thing in this PR
A part of your job is to evaluate the code quality and the maintainability of this PR.
But you may have a headache to only understand the code and all the corner cases.
I'm deeply embarrassed to produce this kind of code quality, maybe after
several nights of insomnia, I'll push another PR to improve it.
For now it's the best thing I can do in a given time.

However, I'll be a pleasure to take all given recommendations and suggestions.

With all my gratitude for this review
Francois

### CODE REVIEW

**Comment by fblackburn1** [comment]
recheck

**Comment by bloom1** [comment]
You forgot a `fixup!` commit in your tree :smiley:

**Comment by fblackburn1** [comment]
> You forgot a `fixup!` commit in your tree smiley

woups fixed ! thanks

**Review by sduthil — APPROVED** [review]

**Comment by pc-m** [comment]
regate

**Pull request merged**
