### PR TITLE
http: remove refresh_tokens from logged content

### PR DESCRIPTION
**Pull request by pc-m**

### CODE REVIEW

**Comment by fblackburn1** [comment]
recheck

**Comment by pc-m** [comment]
recheck

**Comment by fredericlepied** [comment]
recheck

**Comment by fblackburn1** [comment]
@fredericlepied why we don't see this job running on zuul?

**Comment by fblackburn1** [comment]
recheck

**Comment by pc-m** [comment]
regate

**Comment by fblackburn1** [comment]
regate

**Comment by pc-m** [comment]
This is getting painful

**Comment by pc-m** [comment]
regate

**Comment by pc-m** [comment]
This feels like `The Horribly Slow Murderer with the Extremely Inefficient Weapon`
https://www.youtube.com/watch?v=9VDvgL58h_Y

**Comment by fblackburn1** [comment]
regate

**Comment by fblackburn1** [comment]
I'll help you with my spoon

**Comment by pc-m** [comment]
> I'll help you with my spoon

Zuul is holding the spoon here

**Pull request merged**
