### PR TITLE
Use Python 3.9, new workers, and Bullseye dependencies

### PR DESCRIPTION
**Pull request by sopelj**
Depends-on: https://github.com/wazo-platform/wazo-uuid/pull/4
Depends-on: https://github.com/wazo-platform/wazo-dbms/pull/8

### CODE REVIEW

**Comment by sopelj** [comment]
recheck

**Comment by sopelj** [comment]
recheck (update depends on)

**Comment by sopelj** [comment]
recheck (wazo-dbms fixed)

**Comment by fblackburn1** [comment]
recheck

**Comment by jfbourque** [comment]
recheck

**Review by fblackburn1 — DISMISSED** [review]

**Comment by fblackburn1** [comment]
recheck

**Comment by fblackburn1** [comment]
recheck

**Comment by jfbourque** [comment]
recheck

**Comment by jfbourque** [comment]
recheck

**Comment by fblackburn1** [comment]
recheck

**Comment by fblackburn1** [comment]
recheck

**Comment by fblackburn1** [comment]
recheck

**Comment by fblackburn1** [comment]
recheck

**Comment by fblackburn1** [comment]
recheck

**Comment by fblackburn1** [comment]
recheck

**Comment by fblackburn1** [comment]
recheck

**Comment by fblackburn1** [comment]
recheck

**Comment by fblackburn1** [comment]
recheck

**Comment by fblackburn1** [comment]
recheck

**Review by fblackburn1 — APPROVED** [review]

**Pull request merged**
